### ISSUE TITLE
'Invalid line' message when aggregating bed file

### ISSUE THREAD

**Issue by rachadele** [higlass/clodius#124]
Hi,

I am trying to use `clodius aggregate bedfile` on a bed file I made myself, and I keep getting the following message printed to stdout:

```
Invalid line: 1	15543353	15543354
Invalid line: 1	31706778	31706779

Invalid line: 1	31732787	31732788

Invalid line: 1	31872749	31872750

Invalid line: 1	31920245	31920246

Invalid line: 1	33496638	33496639

Invalid line: 1	47684932	47684933

Invalid line: 1	47695094	47695095

```
this repeats for every line in my bed file. 

does this have to do with the format of my file? I am giving it the `--delimiter '\t'` option. when I use `$'t'` as suggested in the higlass manual, clodius is unable to parse my file. I also have a description column in my original bed file, but I removed it to see if it was causing the issue. since I got the error message without the description column, I'm not sure what's causing this.

thx in advance for your help!

**Comment by pkerpedjiev** [comment]
Would you mind trying `--delimiter $'\t'`? 

Also, would it be possible for you to post a snippet of your file online so I can try to reproduce the issue locally?

**Comment by rachadele** [comment]
it works now using that delimiter! thanks

**Comment by pkerpedjiev** [comment]
Great! Sorry about the mistaken docs. I just updated them in the repository and they should be deployed with the next release. Thanks for reporting!
