### ISSUE TITLE
Use requirements.txt to declare Python dependencies

### ISSUE THREAD

**Issue by ngehlenborg** [higlass/clodius#2]
See https://pip.pypa.io/en/stable/user_guide/#requirements-files.

**Comment by nikhil** [comment]
Requirements.txt is already in the repo: [Link](https://github.com/hms-dbmi/clodius/blob/Nikhil/requirements.txt)

**Comment by nikhil** [comment]
Clarification: Requirements.txt is on the Nikhil branch, issue should be resolved after merging.

**Comment by mccalluc** [comment]
Fixed with 72c30eaa3db64c9cdff12303e3387e4c7e15a7d6 long ago.
